/**
 * Claim Flow Configuration
 * Dynamic question engine for different claim types
 */

export const claimFlows = {
  weather_damage: {
    id: 'weather_damage',
    title: 'Weather Damage',
    icon: '🌧️',
    description: 'Storm, flood, hail, or wind damage',
    questions: [
      {
        id: 'incident_description',
        type: 'textarea',
        question: 'What happened?',
        placeholder: 'Describe the weather event and damage in your own words...',
        helper: "Don't worry about formatting. Just explain what happened.",
        required: true,
        minLength: 20,
      },
      {
        id: 'incident_date',
        type: 'date',
        question: 'When did the weather event occur?',
        helper: 'Select the date when the damage happened',
        required: true,
        maxDate: 'today',
      },
      {
        id: 'incident_time',
        type: 'time',
        question: 'Approximate time',
        helper: 'Best estimate is fine',
        required: false,
      },
      {
        id: 'location',
        type: 'text',
        question: 'Where did it happen?',
        placeholder: 'City, suburb, or address',
        helper: 'Your location helps us verify weather data',
        required: true,
      },
      {
        id: 'weather_type',
        type: 'multi-select',
        question: 'What type of weather caused the damage?',
        options: [
          { value: 'storm', label: '⛈️ Storm', icon: '⛈️' },
          { value: 'hail', label: '🧊 Hail', icon: '🧊' },
          { value: 'wind', label: '💨 Strong Wind', icon: '💨' },
          { value: 'flood', label: '🌊 Flood', icon: '🌊' },
          { value: 'lightning', label: '⚡ Lightning', icon: '⚡' },
          { value: 'other', label: '🌪️ Other', icon: '🌪️' },
        ],
        required: true,
      },
      {
        id: 'damage_category',
        type: 'multi-select',
        question: 'What was damaged?',
        options: [
          { value: 'home', label: '🏠 Home/Building', icon: '🏠' },
          { value: 'vehicle', label: '🚗 Vehicle', icon: '🚗' },
          { value: 'electronics', label: '📱 Electronics', icon: '📱' },
          { value: 'furniture', label: '🛋️ Furniture', icon: '🛋️' },
          { value: 'other', label: '📦 Other Property', icon: '📦' },
        ],
        required: true,
      },
      {
        id: 'damage_details',
        type: 'textarea',
        question: 'Describe the damage',
        placeholder: 'What specific items or areas were damaged?',
        helper: 'Be as specific as you can',
        required: true,
        minLength: 20,
      },
      {
        id: 'injuries',
        type: 'boolean',
        question: 'Was anyone injured?',
        required: true,
      },
      {
        id: 'injury_details',
        type: 'textarea',
        question: 'Please describe the injuries',
        placeholder: 'Who was injured and how?',
        required: true,
        minLength: 10,
        conditionalOn: { field: 'injuries', value: true },
      },
      {
        id: 'emergency_repairs',
        type: 'boolean',
        question: 'Did you need to make emergency repairs?',
        helper: 'Temporary repairs to prevent further damage',
        required: true,
      },
      {
        id: 'repair_details',
        type: 'textarea',
        question: 'What emergency repairs were made?',
        placeholder: 'Describe the repairs and who did them',
        required: false,
        conditionalOn: { field: 'emergency_repairs', value: true },
      },
      {
        id: 'estimated_damage',
        type: 'currency',
        question: 'Approximate damage amount?',
        placeholder: '0',
        helper: 'An estimate is okay. You can update this later.',
        required: true,
        min: 0,
      },
    ],
  },

  vehicle_accident: {
    id: 'vehicle_accident',
    title: 'Vehicle Accident',
    icon: '🚗',
    description: 'Car accident or collision',
    questions: [
      {
        id: 'incident_date',
        type: 'date',
        question: 'When did the accident happen?',
        required: true,
        maxDate: 'today',
      },
      {
        id: 'incident_time',
        type: 'time',
        question: 'Approximate time',
        helper: 'Best estimate is fine',
        required: true,
      },
      {
        id: 'location',
        type: 'text',
        question: 'Where did it happen?',
        placeholder: 'Street address or intersection',
        helper: 'Be as specific as possible',
        required: true,
      },
      {
        id: 'incident_description',
        type: 'textarea',
        question: 'What happened?',
        placeholder: 'Describe the accident in your own words...',
        helper: 'Include details about road conditions, traffic, weather',
        required: true,
        minLength: 20,
      },
      {
        id: 'vehicle_status',
        type: 'single-select',
        question: 'Were you driving or parked?',
        options: [
          { value: 'driving', label: '🚗 Driving', icon: '🚗' },
          { value: 'parked', label: '🅿️ Parked', icon: '🅿️' },
          { value: 'stopped', label: '🛑 Stopped at light/sign', icon: '🛑' },
        ],
        required: true,
      },
      {
        id: 'other_vehicle',
        type: 'boolean',
        question: 'Was another vehicle involved?',
        required: true,
      },
      {
        id: 'other_vehicle_details',
        type: 'textarea',
        question: 'Other vehicle details',
        placeholder: 'Make, model, color, registration number if available',
        required: false,
        conditionalOn: { field: 'other_vehicle', value: true },
      },
      {
        id: 'other_driver',
        type: 'boolean',
        question: 'Was another driver involved?',
        required: true,
        conditionalOn: { field: 'other_vehicle', value: true },
      },
      {
        id: 'other_driver_details',
        type: 'textarea',
        question: 'Other driver information',
        placeholder: 'Name, contact, license number if available',
        required: false,
        conditionalOn: { field: 'other_driver', value: true },
      },
      {
        id: 'police_report',
        type: 'boolean',
        question: 'Was a police report filed?',
        required: true,
      },
      {
        id: 'police_report_number',
        type: 'text',
        question: 'Police report number',
        placeholder: 'Enter report number',
        required: false,
        conditionalOn: { field: 'police_report', value: true },
      },
      {
        id: 'injuries',
        type: 'boolean',
        question: 'Was anyone injured?',
        required: true,
      },
      {
        id: 'injury_details',
        type: 'textarea',
        question: 'Please describe the injuries',
        placeholder: 'Who was injured and how?',
        required: true,
        minLength: 10,
        conditionalOn: { field: 'injuries', value: true },
      },
      {
        id: 'vehicle_damage_area',
        type: 'multi-select',
        question: 'What part of your vehicle was damaged?',
        options: [
          { value: 'front', label: 'Front', icon: '🔆' },
          { value: 'rear', label: 'Rear', icon: '🔅' },
          { value: 'left', label: 'Left Side', icon: '◀️' },
          { value: 'right', label: 'Right Side', icon: '▶️' },
          { value: 'roof', label: 'Roof', icon: '🔝' },
          { value: 'windscreen', label: 'Windscreen', icon: '🪟' },
        ],
        required: true,
      },
      {
        id: 'vehicle_driveable',
        type: 'boolean',
        question: 'Is your vehicle still driveable?',
        required: true,
      },
      {
        id: 'estimated_damage',
        type: 'currency',
        question: 'Approximate repair cost?',
        placeholder: '0',
        helper: 'An estimate is okay. Professional assessment will follow.',
        required: true,
        min: 0,
      },
    ],
  },

  theft: {
    id: 'theft',
    title: 'Theft',
    icon: '🔒',
    description: 'Stolen property or burglary',
    questions: [
      {
        id: 'theft_discovery_date',
        type: 'date',
        question: 'When did you discover the theft?',
        required: true,
        maxDate: 'today',
      },
      {
        id: 'theft_discovery_time',
        type: 'time',
        question: 'Approximate time',
        required: false,
      },
      {
        id: 'last_seen_date',
        type: 'date',
        question: 'When did you last see the item(s)?',
        helper: 'This helps establish the timeframe',
        required: true,
        maxDate: 'today',
      },
      {
        id: 'location',
        type: 'text',
        question: 'Where did the theft occur?',
        placeholder: 'Address or location',
        required: true,
      },
      {
        id: 'theft_type',
        type: 'single-select',
        question: 'Type of theft',
        options: [
          { value: 'burglary', label: '🏠 Burglary (forced entry)', icon: '🏠' },
          { value: 'theft', label: '👜 Theft (no forced entry)', icon: '👜' },
          { value: 'vehicle', label: '🚗 Vehicle theft', icon: '🚗' },
          { value: 'robbery', label: '⚠️ Robbery (with threat)', icon: '⚠️' },
        ],
        required: true,
      },
      {
        id: 'stolen_items',
        type: 'textarea',
        question: 'What was stolen?',
        placeholder: 'List all stolen items with descriptions',
        helper: 'Include make, model, serial numbers if known',
        required: true,
        minLength: 20,
      },
      {
        id: 'forced_entry',
        type: 'boolean',
        question: 'Was there evidence of forced entry?',
        helper: 'Broken locks, windows, doors, etc.',
        required: true,
      },
      {
        id: 'entry_details',
        type: 'textarea',
        question: 'Describe the forced entry',
        placeholder: 'How did they gain access?',
        required: false,
        conditionalOn: { field: 'forced_entry', value: true },
      },
      {
        id: 'police_report',
        type: 'boolean',
        question: 'Have you filed a police report?',
        required: true,
      },
      {
        id: 'police_report_number',
        type: 'text',
        question: 'Police report/FIR number',
        placeholder: 'Enter report number',
        required: true,
        conditionalOn: { field: 'police_report', value: true },
      },
      {
        id: 'witnesses',
        type: 'boolean',
        question: 'Were there any witnesses?',
        required: true,
      },
      {
        id: 'witness_details',
        type: 'textarea',
        question: 'Witness information',
        placeholder: 'Names and contact details if available',
        required: false,
        conditionalOn: { field: 'witnesses', value: true },
      },
      {
        id: 'estimated_value',
        type: 'currency',
        question: 'Total estimated value of stolen items',
        placeholder: '0',
        helper: 'Approximate replacement value',
        required: true,
        min: 0,
      },
    ],
  },

  property_damage: {
    id: 'property_damage',
    title: 'Property Damage',
    icon: '🏠',
    description: 'Home or building damage',
    questions: [
      {
        id: 'incident_date',
        type: 'date',
        question: 'When did the damage occur?',
        required: true,
        maxDate: 'today',
      },
      {
        id: 'location',
        type: 'text',
        question: 'Property address',
        placeholder: 'Full address',
        required: true,
      },
      {
        id: 'incident_description',
        type: 'textarea',
        question: 'What happened?',
        placeholder: 'Describe how the damage occurred...',
        required: true,
        minLength: 20,
      },
      {
        id: 'damage_cause',
        type: 'single-select',
        question: 'What caused the damage?',
        options: [
          { value: 'fire', label: '🔥 Fire', icon: '🔥' },
          { value: 'water', label: '💧 Water/Leak', icon: '💧' },
          { value: 'impact', label: '💥 Impact', icon: '💥' },
          { value: 'vandalism', label: '🎨 Vandalism', icon: '🎨' },
          { value: 'structural', label: '🏗️ Structural', icon: '🏗️' },
          { value: 'other', label: '📋 Other', icon: '📋' },
        ],
        required: true,
      },
      {
        id: 'affected_areas',
        type: 'multi-select',
        question: 'Which areas are affected?',
        options: [
          { value: 'roof', label: '🏠 Roof', icon: '🏠' },
          { value: 'walls', label: '🧱 Walls', icon: '🧱' },
          { value: 'floors', label: '▪️ Floors', icon: '▪️' },
          { value: 'windows', label: '🪟 Windows', icon: '🪟' },
          { value: 'doors', label: '🚪 Doors', icon: '🚪' },
          { value: 'plumbing', label: '🚰 Plumbing', icon: '🚰' },
          { value: 'electrical', label: '⚡ Electrical', icon: '⚡' },
          { value: 'contents', label: '📦 Contents', icon: '📦' },
        ],
        required: true,
      },
      {
        id: 'emergency_services',
        type: 'boolean',
        question: 'Were emergency services called?',
        helper: 'Fire, police, ambulance',
        required: true,
      },
      {
        id: 'emergency_report',
        type: 'text',
        question: 'Emergency service report number',
        placeholder: 'Enter report number if available',
        required: false,
        conditionalOn: { field: 'emergency_services', value: true },
      },
      {
        id: 'property_habitable',
        type: 'boolean',
        question: 'Is the property still habitable?',
        required: true,
      },
      {
        id: 'estimated_damage',
        type: 'currency',
        question: 'Estimated repair cost',
        placeholder: '0',
        helper: 'Your best estimate',
        required: true,
        min: 0,
      },
    ],
  },

  medical: {
    id: 'medical',
    title: 'Medical',
    icon: '🏥',
    description: 'Medical expenses or injury',
    questions: [
      {
        id: 'incident_date',
        type: 'date',
        question: 'When did the incident occur?',
        required: true,
        maxDate: 'today',
      },
      {
        id: 'location',
        type: 'text',
        question: 'Where did it happen?',
        placeholder: 'Location of incident',
        required: true,
      },
      {
        id: 'incident_description',
        type: 'textarea',
        question: 'What happened?',
        placeholder: 'Describe the incident that led to medical treatment...',
        required: true,
        minLength: 20,
      },
      {
        id: 'injury_type',
        type: 'multi-select',
        question: 'Type of injury or condition',
        options: [
          { value: 'accident', label: '🤕 Accident', icon: '🤕' },
          { value: 'illness', label: '🤒 Illness', icon: '🤒' },
          { value: 'dental', label: '🦷 Dental', icon: '🦷' },
          { value: 'optical', label: '👓 Optical', icon: '👓' },
          { value: 'other', label: '🏥 Other', icon: '🏥' },
        ],
        required: true,
      },
      {
        id: 'treatment_received',
        type: 'textarea',
        question: 'What treatment did you receive?',
        placeholder: 'Describe medical care, procedures, medications...',
        required: true,
        minLength: 10,
      },
      {
        id: 'healthcare_provider',
        type: 'text',
        question: 'Healthcare provider/facility',
        placeholder: 'Hospital, clinic, or doctor name',
        required: true,
      },
      {
        id: 'treatment_date',
        type: 'date',
        question: 'Date of treatment',
        required: true,
        maxDate: 'today',
      },
      {
        id: 'ongoing_treatment',
        type: 'boolean',
        question: 'Is ongoing treatment required?',
        required: true,
      },
      {
        id: 'estimated_cost',
        type: 'currency',
        question: 'Total medical expenses',
        placeholder: '0',
        helper: 'Include all medical bills and costs',
        required: true,
        min: 0,
      },
    ],
  },
};

export const demoData = {
  weather_damage: {
    incident_description: 'A severe storm with heavy rainfall and strong winds hit our area during the evening. The storm damaged my car parked in the driveway and caused water damage to our balcony and patio furniture.',
    incident_date: '2026-09-28',
    incident_time: '18:30',
    location: 'Pune, Maharashtra',
    weather_type: ['storm', 'wind'],
    damage_category: ['vehicle', 'home', 'furniture'],
    damage_details: 'Car windscreen cracked by flying debris, roof dented from hailstones. Balcony railing damaged, water seeped into walls causing paint damage. Outdoor furniture completely soaked and cushions ruined.',
    injuries: false,
    emergency_repairs: true,
    repair_details: 'Covered broken windscreen with tarp. Called local handyman to seal water entry points on balcony.',
    estimated_damage: 85000,
  },
  vehicle_accident: {
    incident_date: '2026-10-01',
    incident_time: '14:45',
    location: 'MG Road, Bangalore, near Trinity Metro Station',
    incident_description: 'I was driving through the intersection when another vehicle ran a red light and collided with the right side of my car. The impact caused significant damage to the passenger door and wheel.',
    vehicle_status: 'driving',
    other_vehicle: true,
    other_vehicle_details: 'White Honda City, registration KA-03-MN-4567',
    other_driver: true,
    other_driver_details: 'Driver identified as Mr. Raj Kumar, phone: 9876543210',
    police_report: true,
    police_report_number: 'BLR/2026/45678',
    injuries: false,
    vehicle_damage_area: ['right', 'front'],
    vehicle_driveable: false,
    estimated_damage: 125000,
  },
  theft: {
    theft_discovery_date: '2026-09-30',
    theft_discovery_time: '07:00',
    last_seen_date: '2026-09-29',
    location: 'Flat 402, Green Park Apartments, Mumbai',
    theft_type: 'burglary',
    stolen_items: 'MacBook Pro 16-inch (Serial: C02XL8MJLVCG), iPhone 14 Pro, Sony WH-1000XM5 headphones, cash Rs. 15,000, gold chain (approx 10 grams)',
    forced_entry: true,
    entry_details: 'Balcony door lock was broken. They accessed from neighboring balcony.',
    police_report: true,
    police_report_number: 'MUM/2026/23456',
    witnesses: true,
    witness_details: 'Neighbor Mrs. Sharma (Flat 401) heard unusual sounds around 2 AM but did not investigate',
    estimated_value: 285000,
  },
  property_damage: {
    incident_date: '2026-09-27',
    location: '23 Park Street, Kolkata',
    incident_description: 'Water pipe burst in the bathroom overnight causing extensive water damage to the bathroom, hallway, and living room below.',
    damage_cause: 'water',
    affected_areas: ['floors', 'walls', 'plumbing', 'contents'],
    emergency_services: false,
    property_habitable: true,
    estimated_damage: 150000,
  },
  medical: {
    incident_date: '2026-09-25',
    location: 'Home - Chennai',
    incident_description: 'Slipped on wet floor and fractured my left wrist. Required immediate medical attention and surgery.',
    injury_type: ['accident'],
    treatment_received: 'X-ray, CT scan, surgical fixation with plates and screws, pain medication, physiotherapy sessions',
    healthcare_provider: 'Apollo Hospital, Chennai',
    treatment_date: '2026-09-25',
    ongoing_treatment: true,
    estimated_cost: 95000,
  },
};

export function getClaimFlow(claimTypeId) {
  return claimFlows[claimTypeId] || null;
}

export function getDemoData(claimTypeId) {
  return demoData[claimTypeId] || null;
}

export function getAllClaimTypes() {
  return Object.values(claimFlows).map(flow => ({
    id: flow.id,
    title: flow.title,
    icon: flow.icon,
    description: flow.description,
  }));
}
